server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.26.39.200：3306/pay_risk?useUnicode=true&amp;characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: riskuser
    password: 123456
    hikari:
      max-lifetime: 1800000
      connection-timeout: 5000
      idle-timeout: 3600000
      maximum-pool-size: 12
      minimum-idle: 4
      connection-test-query: /**ping*/
  rabbitmq:
    host: testzk01.com
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
    #确认消息已发送到交换机(Exchange)
#    publisher-confirms: true
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
  redis:
    # Redis服务器地址
    cluster:
      nodes: 172.26.39.200:7000,172.26.39.200:7001,172.26.39.200:7002
    # 连接超时时间
    connect-timeout: 30000
    # 设置密码
    password: redis@20200818
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 200



mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


dubbo:
  #注册中心
  registry:
    address: zookeeper://testzk01.com:3180,testzk01.com:3280,testzk01.com:3380
  application:
    name: pay-test
  consumer:
    timeout: 1000000
  provider:
    timeout: 1000000
  protocol:
    accepts: 1000
    threads: 600
    port: 28004
    name: dubbo

#mq:
#  address: testzk01.com:5672
#  username: guest
#  password: guest
#  retry:
#    init: 1000
#    max: 60000
#    num: 2
#    time: 10
#  consumer:
#    max: 1000
#    min: 100
#  test:
#    time: 10
#  vhost: /

